// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAijy-gt4Ap5R4oo3hjDJNtwlXkseE5lgQ',
    appId: '1:25727194230:web:16f805efbc8a27f711bb57',
    messagingSenderId: '25727194230',
    projectId: 'my-re-1f2b3',
    authDomain: 'my-re-1f2b3.firebaseapp.com',
    storageBucket: 'my-re-1f2b3.appspot.com',
    measurementId: 'G-42KGY6LG8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD98Gqi4RQmoMHzaM21Vl6JKkBEEtlVfRU',
    appId: '1:25727194230:android:41c1950e5f738a2511bb57',
    messagingSenderId: '25727194230',
    projectId: 'my-re-1f2b3',
    storageBucket: 'my-re-1f2b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMsr9eVaK_uF4KmfaWeSnOXJP58EhIXPU',
    appId: '1:25727194230:ios:624ff9ac59c4203911bb57',
    messagingSenderId: '25727194230',
    projectId: 'my-re-1f2b3',
    storageBucket: 'my-re-1f2b3.appspot.com',
    iosClientId: '25727194230-d2lkc6rauqudha0p1cuh8u7tr58db62r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fire2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMsr9eVaK_uF4KmfaWeSnOXJP58EhIXPU',
    appId: '1:25727194230:ios:624ff9ac59c4203911bb57',
    messagingSenderId: '25727194230',
    projectId: 'my-re-1f2b3',
    storageBucket: 'my-re-1f2b3.appspot.com',
    iosClientId: '25727194230-d2lkc6rauqudha0p1cuh8u7tr58db62r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fire2',
  );
}
